/* tslint:disable */
// generated by typescript-json-validator
import { inspect } from "util";
import Ajv = require("ajv");
import ConvertConsoleRequest from "./request";
export const ajv = new Ajv({
  allErrors: true,
  coerceTypes: false,
  format: "fast",
  nullable: true,
  unicode: true,
  uniqueItems: true,
  useDefaults: true,
});

ajv.addMetaSchema(require("ajv/lib/refs/json-schema-draft-06.json"));

export { ConvertConsoleRequest };
export const ConvertConsoleRequestSchema = {
  $schema: "http://json-schema.org/draft-07/schema#",
  defaultProperties: [],
  definitions: {
    AcceptedCurrencies: {
      enum: ["BTC", "ETH", "EUR", "GBP", "USD"],
      type: "string",
    },
  },
  properties: {
    amount: {
      type: "number",
    },
    digits: {
      type: "number",
    },
    from: {
      $ref: "#/definitions/AcceptedCurrencies",
    },
    to: {
      $ref: "#/definitions/AcceptedCurrencies",
    },
  },
  required: ["amount", "from", "to"],
  type: "object",
};
export type ValidateFunction<T> = ((data: unknown) => data is T) &
  Pick<Ajv.ValidateFunction, "errors">;
export const isConvertConsoleRequest = ajv.compile(
  ConvertConsoleRequestSchema
) as ValidateFunction<ConvertConsoleRequest>;
export default function validate(value: unknown): ConvertConsoleRequest {
  if (isConvertConsoleRequest(value)) {
    return value;
  } else {
    throw new Error(
      ajv.errorsText(
        isConvertConsoleRequest.errors!.filter((e: any) => e.keyword !== "if"),
        { dataVar: "ConvertConsoleRequest" }
      ) +
        "\n\n" +
        inspect(value)
    );
  }
}
